### ISSUE TITLE
what does next and decoded.id do ??

### ISSUE THREAD

**Issue by Kijacode** [oluwashane/course-rep-api#1]
Hey bro @oluwashane , what does bellow lines means to your api

**const user = await User.findOne({ _id: decoded._id, 'tokens.token': token });
        if (user.role === 'admin') {
            return next()  
        }**

**Comment by Kijacode** [comment]
Also it better if, altleast you add some documentation

**Comment by oluwashane** [comment]
The first line gets the valid user from the jwt token, stored in const decoded.
Then the other part is a middleware for only users with admin access

**Comment by oluwashane** [comment]
Bro I'm still working on the documentation

**Comment by Kijacode** [comment]
@oluwashane  kudos bro and allow me to play with it around

**Comment by oluwashane** [comment]
Sure bro you could add new features
